# Generated by Django 3.0.6 on 2020-06-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shakas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shaka',
            name='key',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='shaka',
            name='message',
            field=models.CharField(max_length=280),
        ),
    ]
