# Generated by Django 3.0.6 on 2020-06-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shakas', '0002_auto_20200611_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shaka',
            name='key',
            field=models.CharField(max_length=60),
        ),
    ]
